-- Split schema entrypoint.
-- Run files in supabase/sql/README.md order.
--
-- This project intentionally keeps SQL split into multiple files:
--   supabase/sql/00_extensions_enums.sql
--   supabase/sql/01_core_tables.sql
--   supabase/sql/02_youth_tables.sql
--   supabase/sql/03_transparency_tables.sql
--   supabase/sql/04_functions_triggers.sql
--   supabase/sql/05_indexes.sql
--   supabase/sql/06_rls_policies.sql
--   supabase/sql/07_seed_data.sql
--   supabase/sql/08_privileges.sql
--   supabase/sql/09_template_seed_data.sql
--   supabase/sql/10_template_seed_data_delete.sql (optional rollback for 09)
--   supabase/sql/11_template_seed_data_pack_b.sql
--   supabase/sql/12_admin_accounts.sql
--   supabase/sql/13_auth_signup_profile_metadata.sql
--   supabase/sql/14_admin_portal_anon_manage_policies.sql (optional for frontend predefined-admin write access)
--   supabase/sql/15_transparency_upload_and_user_manage.sql (optional for transparency file upload + user management in anon-admin mode)
--   supabase/sql/16_user_profile_delete_removes_auth_user.sql (optional but recommended for full user deletion from auth.users)
--   supabase/sql/17_admin_citizen_tickets_anon_manage.sql (optional for Citizen Desk ticket management in anon-admin mode)
--   supabase/sql/18_program_event_precise_location.sql (optional but recommended for precise lat/lng coordinates in programs/events)
--   supabase/sql/19_program_event_time_fields.sql (optional but recommended for start/end time support in programs/events)
--   supabase/sql/20_events_remove_legacy_time_text.sql (optional but recommended to enforce actual event time fields and remove legacy events.time_text)
--   supabase/sql/21_program_registrations.sql (optional but recommended for form-based program registrations)
--   supabase/sql/22_audit_logs.sql (optional but recommended for row-level audit logging of admin-managed data changes)
