begin;

create table if not exists public.roles (
  id smallint generated by default as identity primary key,
  code public.app_role_code not null unique,
  label text not null,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id smallint not null references public.roles(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  assigned_by uuid references auth.users(id) on delete set null,
  primary key (user_id, role_id)
);

create table if not exists public.barangays (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  latitude numeric(9,6),
  longitude numeric(9,6),
  sk_chairperson text,
  youth_population integer not null default 0 check (youth_population >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.offices (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  code text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email citext not null unique,
  full_name text,
  display_name text,
  contact_number text,
  municipality text not null default 'Metro Manila',
  barangay_id uuid references public.barangays(id) on delete set null,
  bio text,
  notifications boolean not null default true,
  show_email_public boolean not null default false,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

commit;
