begin;

create table if not exists public.disclosure_documents (
  id uuid primary key default gen_random_uuid(),
  doc_code text not null unique,
  title text not null,
  document_type public.disclosure_doc_type not null,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  quarter public.quarter_code not null,
  barangay_id uuid references public.barangays(id) on delete set null,
  applies_to_all_barangays boolean not null default false,
  office_id uuid references public.offices(id) on delete set null,
  published_date date not null,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  file_mime_type text,
  storage_path text,
  public_url text,
  source_post_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_downloads (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.disclosure_documents(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  ip_hash text,
  user_agent text,
  downloaded_at timestamptz not null default now()
);

create table if not exists public.barangay_financials (
  id uuid primary key default gen_random_uuid(),
  barangay_id uuid not null references public.barangays(id) on delete cascade,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  month_no smallint not null check (month_no between 1 and 12),
  allocated_amount numeric(14,2) not null default 0 check (allocated_amount >= 0),
  utilized_amount numeric(14,2) not null default 0 check (utilized_amount >= 0),
  sk_budget numeric(14,2) not null default 0 check (sk_budget >= 0),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (barangay_id, fiscal_year, month_no)
);

create table if not exists public.barangay_youth_metrics (
  id uuid primary key default gen_random_uuid(),
  barangay_id uuid not null references public.barangays(id) on delete cascade,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  activities integer not null default 0 check (activities >= 0),
  participants integer not null default 0 check (participants >= 0),
  organizations integer not null default 0 check (organizations >= 0),
  compliance_status public.barangay_compliance_status not null default 'pending',
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (barangay_id, fiscal_year)
);

create table if not exists public.compliance_board_status (
  id uuid primary key default gen_random_uuid(),
  barangay_id uuid not null references public.barangays(id) on delete cascade,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  quarter public.quarter_code not null,
  cbydp public.doc_state not null default 'issue',
  abyip public.doc_state not null default 'issue',
  annual_budget public.doc_state not null default 'issue',
  rcb public.doc_state not null default 'issue',
  mil public.doc_state not null default 'issue',
  remarks text,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (barangay_id, fiscal_year, quarter)
);

create table if not exists public.monthly_compliance (
  id uuid primary key default gen_random_uuid(),
  barangay_id uuid not null references public.barangays(id) on delete cascade,
  fiscal_year integer not null check (fiscal_year between 2000 and 2100),
  month_no smallint not null check (month_no between 1 and 12),
  due_date date not null,
  mfr_status public.submission_state not null default 'missing',
  mil_status public.submission_state not null default 'missing',
  rcb_status public.submission_state not null default 'missing',
  accomplishment_status public.submission_state not null default 'missing',
  census_status public.submission_state not null default 'missing',
  completion_percent smallint not null default 0 check (completion_percent between 0 and 100),
  report_document_id uuid references public.disclosure_documents(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (barangay_id, fiscal_year, month_no)
);

create table if not exists public.ticket_types (
  id smallint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create sequence if not exists public.youth_ticket_ref_seq start with 100000 increment by 1;

create table if not exists public.youth_tickets (
  id uuid primary key default gen_random_uuid(),
  reference_no text not null unique,
  type_id smallint not null references public.ticket_types(id) on delete restrict,
  subject text not null,
  message text not null,
  requester_email citext not null,
  requester_name text,
  requester_contact text,
  status public.ticket_status not null default 'received',
  priority smallint not null default 3 check (priority between 1 and 5),
  created_by_user_id uuid references auth.users(id) on delete set null,
  assigned_to_user_id uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

commit;

